<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<script src="{{asset('assets/bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/bs-init.js')}}"></script>
<script src="{{asset('assets/js/File-Input---Beautiful-Input--Button-Approach-Jasny-Bootstrap.js')}}"></script>
<script src="{{asset('assets/js/Grid-and-List-view-V10.js')}}"></script>
<script src="{{asset('assets/js/MUSA_carousel-extended.js')}}"></script>
<script src="{{asset('assets/js/Parallax-Scrolling-Horizontal-plus-Vertical.js')}}"></script>
{{-- <script src="{{asset('assets/js/Ludens---1-Dark-mode-Index-Table-with-Search-Filters-1.js')}}"></script>
<script src="{{asset('assets/js/Ludens---1-Dark-mode-Index-Table-with-Search-Filters-2.js')}}"></script> --}}
<script src="{{asset('assets/js/Ludens---1-Dark-mode-Index-Table-with-Search-Filters.js')}}"></script>
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
{{-- <script src="{{asset('assets/vuejs/vue.global.js')}}"></script> --}}
{{-- <script src="{{asset('assets/vuejs/prueba.vue')}}"></script> --}}